from __future__ import annotations

import numpy as np
from statsmodels.tsa.ar_model import AutoReg

from analysis.numerical_spectral_verification import estimate_alpha

MAX_AR_ORDER = 20
MIN_AR_ORDER = 1
BURN_IN = 1000
MIN_VALID_SURROGATES = 200

def _as_series(series):
    x = np.asarray(
        series,
        dtype=np.float64,
    )

    if x.ndim != 1:
        raise ValueError(
            "series must be one-dimensional"
        )

    if len(x) < 256:
        raise ValueError(
            "series too short for stochastic-null inference"
        )

    if not np.all(np.isfinite(x)):
        raise ValueError(
            "series contains non-finite values"
        )

    return x

def _stationary_fit(series):
    x = _as_series(series)
    candidates = []

    max_order = min(
        MAX_AR_ORDER,
        max(
            MIN_AR_ORDER,
            len(x) // 10,
        ),
    )

    # IMPORTANT:
    # Every candidate order must be evaluated on the same
    # effective observations. Without a fixed hold_back,
    # AutoReg uses a different number of observations for
    # different lag orders, making information-criterion
    # comparisons across orders non-comparable.
    hold_back = int(max_order)

    for order in range(
        MIN_AR_ORDER,
        max_order + 1,
    ):
        try:
            fit = AutoReg(
                x,
                lags=order,
                trend="c",
                old_names=False,
                hold_back=hold_back,
            ).fit()
        except Exception:
            continue

        roots = np.asarray(
            fit.roots,
            dtype=np.complex128,
        )

        if (
            roots.size != order
            or not np.all(np.abs(roots) > 1.0)
        ):
            continue

        if not np.isfinite(float(fit.aic)):
            continue

        candidates.append(
            (
                float(fit.aic),
                order,
                fit,
            )
        )

    if not candidates:
        raise RuntimeError(
            "no stationary AR(p) candidate could be fitted"
        )

    _, order, fit = min(
        candidates,
        key=lambda item: item[0],
    )

    return order, fit

def _simulate_from_fit(
    fit,
    n,
    rng,
    burn_in=BURN_IN,
):
    params = np.asarray(
        fit.params,
        dtype=np.float64,
    )

    order = int(
        fit.model._maxlag
    )

    intercept = float(
        params[0]
    )

    phi = np.asarray(
        params[1:1 + order],
        dtype=np.float64,
    )

    sigma = float(
        np.sqrt(fit.sigma2)
    )

    total = (
        int(n)
        + int(burn_in)
    )

    eps = rng.normal(
        0.0,
        sigma,
        total,
    )

    x = np.zeros(
        total,
        dtype=np.float64,
    )

    denom = (
        1.0
        -
        float(np.sum(phi))
    )

    initial = (
        intercept / denom
        if abs(denom) > 1e-8
        else 0.0
    )

    x[:order] = initial

    for i in range(
        order,
        total,
    ):
        x[i] = (
            intercept
            +
            np.dot(
                phi,
                x[i - order:i][::-1],
            )
            +
            eps[i]
        )

    return x[burn_in:]

def parametric_short_memory_null(
    series,
    observed_alpha,
    rng,
    trials=1000,
):
    """
    Primary stochastic-null gate.

    Scientific endpoint
    -------------------

    The procedure does NOT establish the broad proposition
    that the observed series is "adequately represented" by
    an AR(p) model.

    Instead, it performs a declared parametric bootstrap
    comparison of the canonical observed spectral exponent
    against spectral exponents generated by a fitted,
    stationary Gaussian AR(p) short-memory surrogate model.

    The AR order p is selected by AIC over 1..MAX_AR_ORDER
    on the observed series.

    Each surrogate is then independently refitted using the
    same stationary AIC procedure before its alpha is estimated.

    The primary alternative is:

        observed canonical alpha > null-generated alpha

    Therefore the primary p-value is the upper-tail exceedance
    probability:

        P(null_alpha >= observed_alpha)

    with the Monte-Carlo add-one correction.

    This result is the primary stochastic-null gate.

    It is not a test of generic model adequacy, causation,
    universality, mechanism, or HCM theory.

    The protocol is currently classified by strict_claim.json
    as a prospective repair after observation and must not be
    described as preregistered confirmation.
    """

    x = _as_series(series)

    observed_alpha = float(
        observed_alpha
    )

    trials = int(trials)

    if not np.isfinite(
        observed_alpha
    ):
        raise ValueError(
            "observed_alpha must be finite"
        )

    if trials < MIN_VALID_SURROGATES:
        raise ValueError(
            f"trials must be >= "
            f"{MIN_VALID_SURROGATES}"
        )

    selected_order, fitted = (
        _stationary_fit(x)
    )

    null_alphas = []
    selected_orders = []

    refit_failures = 0
    alpha_failures = 0

    for _ in range(trials):
        surrogate = _simulate_from_fit(
            fitted,
            len(x),
            rng,
        )

        try:
            refit_order, _ = (
                _stationary_fit(
                    surrogate
                )
            )
        except Exception:
            refit_failures += 1
            continue

        try:
            alpha = estimate_alpha(
                surrogate
            )
        except Exception:
            alpha_failures += 1
            continue

        if np.isfinite(alpha):

            null_alphas.append(
                float(alpha)
            )

            selected_orders.append(
                int(refit_order)
            )

    null = np.asarray(
        null_alphas,
        dtype=np.float64,
    )

    valid = int(
        null.size
    )

    if valid < MIN_VALID_SURROGATES:
        return {
            "valid": False,

            "reason":
                "insufficient_valid_surrogates",

            "scientific_role":
                "primary_stochastic_null_gate",

            "support_eligible":
                False,

            "null_model":
                "stationary_gaussian_ar_p_aic",

            "test_endpoint":
                "canonical_primary_alpha",

            "alternative":
                "greater_than_null",

            "tail":
                "upper",

            "selected_order":
                int(selected_order),

            "max_order":
                int(MAX_AR_ORDER),

            "order_selection_diagnostic": {
                "selected_at_boundary":
                    bool(
                        selected_order
                        ==
                        MAX_AR_ORDER
                    ),

                "surrogate_boundary_fraction":
                    None,

                "refit_failures":
                    int(refit_failures),

                "alpha_estimation_failures":
                    int(alpha_failures),

                "scientific_role":
                    "diagnostic_only",
            },

            "trials_requested":
                int(trials),

            "null_samples":
                valid,

            "observed_alpha":
                observed_alpha,
        }

    exceedances = int(
        np.sum(
            null >= observed_alpha
        )
    )

    p_value = float(
        (exceedances + 1)
        /
        (valid + 1)
    )

    return {
        "valid": True,

        "scientific_role":
            "primary_stochastic_null_gate",

        "support_eligible":
            True,

        "null_model":
            "stationary_gaussian_ar_p_aic",

        "null_hypothesis":
            "under the declared fitted stationary "
            "Gaussian AR(p) surrogate-generation and "
            "refitting procedure, with p selected by "
            "AIC over 1..20, the canonical primary "
            "spectral exponent is not greater than "
            "the corresponding null distribution "
            "under the stated upper-tail endpoint test",

        "test_endpoint":
            "canonical_primary_alpha",

        "alternative":
            "greater_than_null",

        "tail":
            "upper",

        "selection_rule": {
            "criterion":
                "AIC",

            "min_order":
                int(MIN_AR_ORDER),

            "max_order":
                int(MAX_AR_ORDER),

            "trend":
                "constant",

            "stationarity_required":
                True,
        },

        "surrogate_generation": {
            "family":
                "stationary_gaussian_AR_p",

            "order_selected_by":
                "AIC",

            "order_selection_range": [
                int(MIN_AR_ORDER),
                int(MAX_AR_ORDER),
            ],

            "burn_in":
                int(BURN_IN),

            "refit_each_surrogate":
                True,

            "innovation_distribution":
                "Gaussian",

            "scientific_role":
                "primary_null_generation",
        },

        "selected_order":
            int(selected_order),

        "trials_requested":
            int(trials),

        "null_samples":
            valid,

        "exceedances":
            exceedances,

        "p_value_mc_add_one":
            p_value,

        "observed_alpha":
            observed_alpha,

        "null_mean":
            float(
                np.mean(null)
            ),

        "null_median":
            float(
                np.median(null)
            ),

        "null_std":
            float(
                np.std(
                    null,
                    ddof=1,
                )
            ),

        "null_q05":
            float(
                np.quantile(
                    null,
                    0.05,
                )
            ),

        "null_q50":
            float(
                np.quantile(
                    null,
                    0.50,
                )
            ),

        "null_q95":
            float(
                np.quantile(
                    null,
                    0.95,
                )
            ),

        "selected_order_median":
            float(
                np.median(
                    selected_orders
                )
            ),

        "selected_order_max":
            int(
                np.max(
                    selected_orders
                )
            ),

        "order_selection_diagnostic": {
            "selected_at_boundary":
                bool(
                    selected_order
                    ==
                    MAX_AR_ORDER
                ),
            
            "boundary_warning":
                (
                    "AIC selected the maximum declared AR order. "
                    "This is a model-capacity diagnostic and does not "
                    "constitute evidence against or for the scientific claim."
                    if selected_order == MAX_AR_ORDER
                    else None
                ),

            "surrogate_boundary_fraction":
                float(
                    np.mean(
                        np.asarray(
                            selected_orders
                        )
                        ==
                        MAX_AR_ORDER
                    )
                ),

            "refit_failures":
                int(refit_failures),

            "alpha_estimation_failures":
                int(alpha_failures),

            "scientific_role":
                "diagnostic_only",

            "interpretation":
                "The AIC order-selection procedure "
                "is reported for transparency. Reaching "
                "the declared maximum order does not "
                "reject the primary null and does not "
                "by itself invalidate the test. A high "
                "boundary fraction indicates that the "
                "declared order range requires calibration "
                "before stronger model-adequacy conclusions "
                "are made.",
        },

        "reject_at_0_05":
            bool(
                p_value <= 0.05
            ),

        "permutation_null_is_primary":
            False,
    }
