name: Validate Stress

on:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  stress:
    runs-on: ubuntu-latest
    env:
      STRESS: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run validate
